services:
  db:
    image: postgres:11
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: socialhub_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b '0.0.0.0'"
    volumes:
      - .:/socialhub
      - ./config/master.key:/app/config/master.key
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: socialhub_development

  test:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rspec"
    volumes:
      - .:/app
      - ./config/master.key:/app/config/master.key
    depends_on:
      - db
    environment:
      RAILS_ENV: test
      DATABASE_HOST: db
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: socialhub_test

volumes:
  postgres_data:
